version: 2
updates:
  - package-ecosystem: npm
    directory: /bot
    schedule:
      interval: weekly
    groups:
      npm_and_yarn:
        patterns:
          - "*"
    open-pull-requests-limit: 5
    reviewers:
      - Petite-Brioche0

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
